# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNApp
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  target 'RNAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNApp-tvOS

  target 'RNApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
